### ISSUE TITLE
♻️Commenting the project codes

### ISSUE THREAD

**Issue by ismailmunyentwari9** [HERMON-1995/To-do-list-project#12]
🧑🏼‍🤝‍🧑🏼  Dear @HERMON-1995 I really liked the way your codes are clean and clear to understand and even efficient for desired output. However you need to add the `comments` in your codes to help anyone who need to learn from you
Thank you @HERMON-1995..
Happy CODING DAY ☺

**Comment by HERMON-1995** [comment]
Thank you I will do that. 😊
